version: '3.8'

services:
  api:
    build:
      context: ./src
      dockerfile: SentimentSuite.Video.Api/Dockerfile
    ports:
      - "5156:8080"
    depends_on:
      - summarizer
      - mongo
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LocalSummary__BaseUrl=http://summarizer:8000
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - MongoDB__DatabaseName=SentimentSuite
      - Redis__ConnectionString=redis:6379
    networks:
      - app-network

  summarizer:
    build:
      context: ./src/SentimentSuite.Summarizer.PyService
    ports:
      - "8000:8000"
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - app-network

volumes:
  mongo_data:
  redis_data:

networks:
  app-network:
    driver: bridge